### ISSUE TITLE
Unifying the use of MACROs and APIs in pdc_malloc.h all over the project

### ISSUE THREAD

**Issue by zhangwei217245** [hpc-io/pdc#155]
In pdc_malloc.h, we provided both APIs and MACROs for memory allocation, but it seems that MACROs are not necessary. 

We need to take some time to evaluate whether we should take only APIs or only MACROs when it is in use. Once decided, we need to unify the use of them either in APIs or MACROs, throughout the project.

**Comment by jeanbez** [comment]
Let's switch to using the PDC malloc ones instead of the macros and directly calling malloc.

**Comment by jeanbez** [comment]
https://github.com/hpc-io/pdc/blob/stable/src/commons/utils/include/pdc_malloc.h

**Comment by jeanbez** [comment]
@hyunjuooh have you opened the new PR with this fix?

**Comment by hyunjuooh** [comment]
I have opened the new PR today. Thank you for the notification.
