### ISSUE TITLE
HDF5 cannot be found for pdc_import.c and pdc_export.c when BUILD_TOOLS=ON

### ISSUE THREAD

**Issue by zhangwei217245** [hpc-io/pdc#160]
When compiling PDC project, if BUILD_TOOLS is set to ON, the compilation of PDC may fail since HDF5 is not able to be found. Proper use of FindHDF5 needs to be included in the CMakeLists.txt under src/tools so that those two artifacts gets compiled. 

Command tried:

`cmake -DBUILD_MPI_TESTING=ON -DBUILD_SHARED_LIBS=ON -DPDC_SERVER_CACHE=ON -DBUILD_TESTING=ON -DCMAKE_INSTALL_PREFIX=$PDC_DIR -DPDC_ENABLE_MPI=ON -DMERCURY_DIR=$MERCURY_DIR -DCMAKE_C_COMPILER=mpicc -DMPI_RUN_CMD="srun -A m2621 --qos=debug --constraint=cpu --tasks-per-node=64" -DCMAKE_INSTALL_PREFIX=$PDC_DIR -DBUILD_TOOLS=ON ../`

**Comment by zhangwei217245** [comment]
![image](https://github.com/hpc-io/pdc/assets/346451/752bc554-e0fa-4673-a11e-d60b3fd27ccf)

**Comment by houjun** [comment]
You can compile it by doing "export HDF5_DIR=/path/to/hdf5/install" before the cmake command.

**Comment by zhangwei217245** [comment]
when cray-parallel-hdf5 module is loaded, $HDF5_DIR is already set. CMake was not able to find HDF5 because the compiler used in NERSC-ci was 'mpicc' instead of 'cc'. 

We should use cc instead. This issue was fixed in PR #161
