### ISSUE TITLE
PDC installation in MacOS from source gives mercury related errors

### ISSUE THREAD

**Issue by jeanbez** [hpc-io/pdc#163]
PDC develop/stable version in MacOS Sonoma:

```
[ 10%] Built target pdc_commons
[ 11%] Built target dart_core_test
[ 12%] Built target query_utils_test
[ 13%] Linking C shared library ../../bin/libpdc.dylib
Undefined symbols for architecture x86_64:
  "_hg_thread_mutex_init", referenced from:
      _PDC_register_type in pdc_interface.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/libpdc.0.1.0.dylib] Error 1
make[1]: *** [src/api/CMakeFiles/pdc.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by zhangwei217245** [comment]
is this on Apple Silicon (if MacOS Sonoma, highly likely it is only supporting Apple Silicon)? What is the command line for cmake configuration?

**Comment by jeanbez** [comment]
@zhangwei217245  nope, Intel's. I'm already looking into this issue. I've solved most of the issues, but there are still some pending. I'll push the changes once they are stabilized.

**Comment by jeanbez** [comment]
This has been fixed and merged with https://github.com/hpc-io/pdc/pull/172
