### ISSUE TITLE
BDCATS Batch Code Bug

### ISSUE THREAD

**Issue by wangvsa** [hpc-io/pdc#191]
**Bug Report**

Replace `PDC_WRITE` with `PDC_READ` for all create calls.

https://github.com/hpc-io/pdc/blob/a47af2299365d62807e8f675b3296d87ddf41af6/examples/bdcats_batch.c#L247

Replace `writing` with `reading`.
https://github.com/hpc-io/pdc/blob/a47af2299365d62807e8f675b3296d87ddf41af6/examples/bdcats_batch.c#L107

bdcats.c uses `PDCobj_open()` but here we use `PDCobj_open_col()`. Should we keep them the same?

**Comment by houjun** [comment]
Hi @wangvsa, thanks for catching the bug with bdcats_batch, can you create a pull request to replace the PDC_WRITE with PDC_READ?
I'd propose to use PDCobj_open_col() for both bdcats and bdcats_batch.
