### ISSUE TITLE
Integration of features used with EQSIM workflow

### ISSUE THREAD

**Issue by houjun** [hpc-io/pdc#194]
**What does this feature solve or improve?**

ZFP compression
Data querying

**Describe the solution you'd like**

When compression is enabled in PDC, automatically compress/decompress data before writing / after reading from the file system.
Data querying needs to work with the new region APIs.

**Describe alternatives you've considered**
N/A

**Additional Information**

**Comment by jeanbez** [comment]
Related to #213
