### ISSUE TITLE
Lustre parameters auto-configuration

### ISSUE THREAD

**Issue by wangvsa** [hpc-io/pdc#43]
Currently some of the Lustre parameters like stripe size and stripe count are configured in a static way that is specific to Cori.
We should be able to automatically detect the system information (.e.,g number of OSTs) and configure those parameters dynamically.

**Comment by houjun** [comment]
Fixed in develop branch [commit](https://github.com/hpc-io/pdc/commit/791ce31f0ad07923318300d5cb9f0c744c66e0d9), will close this once it is merged to stable
