### ISSUE TITLE
Incorrect path in pdc-config.cmake to pdc-targets.cmake

### ISSUE THREAD

**Issue by JLaoo** [hpc-io/pdc#58]
In the current version of the develop branch, the current auto generated path to `pdc-targets.cmake` is incorrect and points to where `pdc-targets.cmake` is located in the current stable branch. The current path is `include(${SELF_DIR}/api/pdc-targets.cmake)` but it should be `include(${SELF_DIR}/src/api/pdc-targets.cmake)`. This issue results in external projects that depend on an already built PDC to error when compiling.

**Comment by houjun** [comment]
Opened a new issue for compiling PDC tools
